title: Markov Chain Monte Carlo
description: Đây là trang chứa những thứ Tân học được về Xích Markov Monte Carlo (MCMC). Trích dẫn: 
theme: just-the-doc

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
